# Generated by Django 4.0.3 on 2022-04-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_cents', models.IntegerField()),
                ('recurring', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='SisterOrg',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('join_date', models.DateField()),
                ('affiliation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neighborhoods.sisterorg')),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodImages',
            fields=[
                ('link', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='FundingGoalImages',
            fields=[
                ('link', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('funding_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.fundinggoal')),
            ],
        ),
        migrations.AddField(
            model_name='fundinggoal',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollars'), ('CAD', 'Canadian Dollars')], max_length=3)),
                ('recurring', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='neighborhoods.supporter')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='neighborhoods.neighborhood')),
            ],
        ),
    ]
